### ISSUE TITLE
Add a command for configuration

### ISSUE THREAD

**Issue by Jaykul** [PowerShell/PowerShellForGitHub#24]
It's a bit silly to have to edit a file (in Program Files?) by hand, for a PowerShell module.
 
Additionally, the setting really should go in AppData, so multiple users can share a single install of the module.

**Comment by felixfbecker** [comment]
Related https://github.com/PowerShell/PowerShellForGitHub/issues/26

**Comment by HowardWolosky** [comment]
Agreed. Fixing.

**Comment by HowardWolosky** [comment]
Fixed in 0.2.0
