### ISSUE TITLE
macOS/Linux CI

### ISSUE THREAD

**Issue by felixfbecker** [PowerShell/PowerShellForGitHub#28]
Simple: https://github.com/pester/Pester/blob/master/.travis.yml
Advanced: https://github.com/aaronpowell/ps-nvm/blob/master/.travis.yml

**Comment by HowardWolosky** [comment]
@felixfbecker  - it's not clear what you're trying to suggest here.  If you can provide more information on what this issue is specifically trying to suggest, please add and we can re-activate this issue.
