### ISSUE TITLE
Enhance Get-GitHubRepositoryTag cmdlet by providing ability to filter results by TagName

### ISSUE THREAD

**Issue by tristanbarcelon** [PowerShell/PowerShellForGitHub#46]
This module fits very close to what I needed when querying available tags before finally downloading a release asset using the releases api. It would be even better if there was a way to filter out the tag results by providing an optional parameter to Get-GitHubRepositoryTag:

1). [string[]] TagName
When provided, filter the results by tags that have an exact match with values in the array.

I'm intending to use this cmdlet to find the existence of matching tags. When they do exist, then I can call the releases api and filter by assets names to download.

Thanks in advance.

**Comment by HowardWolosky** [comment]
Thanks for the suggestion, Tristan.  The beauty of PowerShell is how easily it lets you process data through piping.  In this case, the way to achieve what you want is to filter the results through `Where-Object` afterwards.  Example:

```powershell
Get-GitHubRepositoryTag -OwnerName PowerShell -RepositoryName PowerShellForGitHub | | Where-Object { $_.name -like '0.3.*' }
```
Given that this can be done naturally through PowerShell via post-processing, it's not something that makes sense to add explicitly to the function itself.

Thanks!

**Comment by HowardWolosky** [comment]
To even more closely match your explicit request:

```powershell
$tagNames = @('0.3.0', '0.2.0')
$tags = Get-GitHubRepositoryTag -OwnerName PowerShell -RepositoryName PowerShellForGitHub
$tags | Where-Object { $_.name -in $tagNames }
```

**Comment by tristanbarcelon** [comment]
I agree with your suggestion and it works well for the purpose mentioned. Thank you.
