### ISSUE TITLE
GitLab Token issue on ConvertTo-SecureString 

### ISSUE THREAD

**Issue by NealWalters** [PowerShell/PowerShellForGitHub#87]
Is this module compatible with GitLab? 
I have a token that was workign with PSGitLab, but I haven't found a clone feature on that module. 

I have modified the token, but it looks roughly like the one below: 

$secureString = ('abCdEf1gHIJKL2m_123A' | ConvertTo-SecureString)

Results in this error: 

ConvertTo-SecureString : Input string was not in a correct format.
At line:1 char:43
+ $secureString = ('abCdEf1gHIJKL2m_123A' | ConvertTo-SecureString)
+                                           ~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [ConvertTo-SecureString], FormatException
    + FullyQualifiedErrorId : System.FormatException,Microsoft.PowerShell.Commands.ConvertToSecureStringCommand

Thanks,
Neal Walters

**Comment by HowardWolosky** [comment]
Hi Neal,

The GitLab and GitHub API's are not quite the same, so this module would not work with it.

As an aside, you can't create a secure string that way.  You don't need a SecureString to work with this module since it directly works with a `PSCredential` object (refer to the [Configuration] (https://github.com/PowerShell/PowerShellForGitHub#configuration) documentation).

If you really wanted to get a SecureString for some other purpose, you'd get it by doing the following:

```powershell
$cred = Get-Credential
# Enter anything in for username and then enter in your token as the password
$cred.Password # this will be the SecureString
$cred.Password | ConvertFrom-SecureString # this will give you an ASCII representation of the secure string which you can then convert back to a secure string using your previously referenced ConvertTo-SecureString
```

**Comment by NealWalters** [comment]
Thanks,  I'm playing with PSGitLab as well, but can't find a clone/commit function with them. Seems like standard GitHub command line works with GitLab, so I thought maybe the interface was close enough. 

By the way, I got that "SecureString" code by doing the following: 

Get-Help Set-GitHubAuthentication -ShowWindow
It's Example #2.  So I think it's code you provided in your docs, am I wrong? 

Neal

**Comment by HowardWolosky** [comment]
Thanks for pointing out the [confusing example](https://github.com/PowerShell/PowerShellForGitHub/blob/master/GitHubConfiguration.ps1#L812).  That should have been more clear that `<Your Access Token>` should have already been in a secure string form.  I'll get that example cleaned-up a bit.

As for your core concern, cloning and committing should be done directly through [git itself](https://git-scm.com/).  Where a module like this or `PSGitLab` come into play is how you further manage a _project_ (like controlling issues, creating forks, managing teams/orgs, etc...).  [Cloning](https://www.git-scm.com/docs/git-clone) and [committing](https://www.git-scm.com/docs/git-commit) are core `git` commands that any `git.exe` should be able to handle on any repo, regardless of where it's hosted (GitHub, DevOps, GitLab, etc...).
